abertura 
{
    leandro 
    {
        primeiro 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
        segundo 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
        terceiro 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
    }    
    lucas 
    {
        primeiro 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
        segundo 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
        terceiro 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
    }    
    thiago 
    {
        primeiro 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
        segundo 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
        terceiro 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
    }    
    nil 
    {
        primeiro 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
        segundo 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
        terceiro 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
    }    
    vencedor 
    {
        primeiro 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
        segundo 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
        terceiro 
        {
            id
            nomeJ
            nomeE
            imagem
            ponto
        }
    }
}